apiVersion: theme.halo.run/v1alpha1
kind: Theme
metadata:
  name: halo-theme-vapor
spec:
  displayName: Vapor-Gridfriend
  author:
    name: SCOTT Studio
    website: https://halo.scott-studio.cn
  description: 一个极简风格的Halo主题 - Gridfriend版本
  logo: "/themes/halo-theme-vapor/assets/imgs/vapor.png"
  homepage: https://halo.scott-studio.cn
  repo: https://github.com/iscottt/halo-theme-vapor
  issues: https://github.com/iscottt/halo-theme-vapor/issues
  settingName: "theme-vapor-setting"
  configMapName: "theme-vapor-setting-configMap"
  version: "1.0.9"
  requires: ">=2.0.0"
  license:
    - name: "Apache License 2.0"
      url: "https://github.com/iscottt/halo-theme-vapor/blob/main/LICENSE"
